### PR TITLE
improve: README.md

### PR DESCRIPTION
**Pull request by Meltartica**
## Changes

- added badges at the start of the repo by (Releases, License, Localization, Nightly Release (Actions), Issues Amount, Pull Request Amount, Discord and Telegram Channel links)
- added more details about the dependencies.
- rewrite some sentences to be more concise.
- Added more detail to the note (talk about unstable release can found in Action page but only install at discretion).

## Why 

- To prepare for the release of the project to the public.

## Checkmarks

- [X] The modified functions have been tested.
- [X] Used the same indentation as the rest of the project.
- [X] Updated documentation (changelog).

## Additional information

If you have any additional information, write it here

### CODE REVIEW

**Review by ThePedroo — COMMENTED** [review]
In my opinion, while I liked the tables for dependencies, I feel the "buttons" gives an unprofessional look to the README. Projects like Linux Kernel, cURL doesn't have any actual buttons, only their project logos and other things. Magisk, in the other side, has only one.

I'd like to hear what @RainyXeon has to say about those too.

**Review by RainyXeon — COMMENTED** [review]
I agree with @ThePedroo, maybe readme need to reduce buttons a bit

**Comment by Meltartica** [comment]
@ThePedroo @RainyXeon thinking bout it yeah true, wait imma come up with an updated one.

**Comment by Meltartica** [comment]
I have made the recommended changes. For your approval, @RainyXeon @ThePedroo

**Review by RainyXeon — APPROVED** [review]
LGTM, wait for @ThePedroo

**Comment by ThePedroo** [comment]
I forgot about this, sorry

**Pull request merged**
