### PR TITLE
Full Chinese Translation.

### PR DESCRIPTION
**Pull request by SheepChef**
## Changes

Translate all currently existing English strings to Chinese.

## Why 

Translation work.

## Checkmarks

- The modified functions have been tested.
- Used the same indentation as the rest of the project.
- Updated documentation (changelog).

## Additional information

Nothing additional, just translation.

### CODE REVIEW

**Review by RainyXeon — APPROVED** [review]
LGTM, wait for Pedro

**Review by ThePedroo — CHANGES_REQUESTED** [review]
Add your name in: https://github.com/PerformanC/ReZygisk/blob/add/webui/webroot/js/language.js#L52

**Review by SheepChef — COMMENTED** [review]
Language.js Changed.

**Review by ThePedroo — APPROVED** [review]
LGTM

**Pull request merged**
