### PR TITLE
Improve/simplify description in APatch and KSU backed systems

### PR DESCRIPTION
**Pull request by ThePedroo**
## Changes

This PR both improves the indentation of Rust code and also simplifies the module description when using a root impl that support the future web ui.

## Why 

This allows it to look nicer on module list, keeping it minimum, and only showing more info in the web UI.

## Checkmarks

- [X] The modified functions have been tested.
- [X] Used the same indentation as the rest of the project.
- [X] Updated documentation (changelog).

### CODE REVIEW

**Comment by CaptainThrowback** [comment]
In the current state, the description field on the module page is still a bit busy, with the monitor and daemon32/64 statuses all still there. If the idea is for the user to be able to get a quick view of whether ReZygisk is working, then my suggestion would be to instead use the status that the WebUI uses, where it says "Working", "Partially Working", or "Unknown". The monitor and daemon details should be accessible through the WebUI, so including them in the description would be unnecessary and redundant.

So the status would look like this in the case where everything is working as expected:
Screenshot_20240714-120949
Screenshot_20240714-120955

(Obviously you can use whatever emoji you want for the status, I just chose the green check mark because I had it handy. You could also use no emoji as well)

I hope that clarifies my suggestion.

**Comment by ThePedroo** [comment]
I understand your point and I agree with it, I'll be working on it

**Comment by ThePedroo** [comment]
This WILL be delayed in favor of #38.

**Comment by ThePedroo** [comment]
The goal of this PR will be done in #38

**Pull request closed without merging**
