### PR TITLE
Re-write Zygiskd

### PR DESCRIPTION
**Pull request by ThePedroo**
## Changes

This PR focus on the change of zygiskd from Rust to C99.

## Why 

C99 has been proven to be a more robust and future-proof language, also being more performant and capable.

## Checkmarks

- [x] The modified functions have been tested.
- [x] Used the same indentation as the rest of the project.

## Additional information

Also will allow the use of multiple root implementation by just ignoring deny list.

### CODE REVIEW

**Comment by nino1802** [comment]
Nice

**Comment by Zdendaop** [comment]
> ## Changes
> 
> This PR focus on the change of zygiskd from Rust to C99.
> 
> ## Why 
> 
> C99 has been proven to be a more robust and future-proof language, also being more performant and capable.
> 
> ## Checkmarks
> 
> - [x] The modified functions have been tested.
> - [x] Used the same indentation as the rest of the project.
> 
> ## Additional information
> 
> Also will allow the use of multiple root implementation by just ignoring deny list.
>

**Review by Zdendaop — APPROVED** [review]

**Comment by ThePedroo** [comment]
Landed on 97af7fe2da7dfac94a895b0b545ab4537bceadea

**Comment by Ammar64** [comment]
How is C99 more future-proof than rust?

Isn't rust the FAST and the SAFE language?
I always see people migrate from other languages to rust.
you are the first one to do the oppsite 😅

**Pull request closed without merging**
