### PR TITLE
add: *not really* material you designed (nmd3 / nmyd) webui

### PR DESCRIPTION
**Pull request by RainyXeon**
## Changes

This commit will add webui support for ReZygisk

## Why 

With webui, user will be easier to manage ReZygisk

## Checkmarks

- [x] The modified functions have been tested.
- [x] Used the same indentation as the rest of the project.
- [x] Updated documentation (changelog).

## Additional information

If you have any additional information, write it here

### CODE REVIEW

**Comment by ThePedroo** [comment]
For translators that will update the translations: No need to literal translate it, modify as much as needed to make it sound natural -- like it was made in that language :^)

**Comment by CaptainThrowback** [comment]
WebUI won't load when Multiple root implementations are used (note that daemon also crashes). See attached video.

https://github.com/user-attachments/assets/ace1a3db-5484-4f74-b4ec-1dfa661499e7

**Comment by ThePedroo** [comment]
> WebUI won't load when Multiple root implementations are used (note that daemon also crashes). See attached video.
> 2024-07-14-22-23-37.mp4

Mind posting results of following commands on adb shell or Termux (w/root)?:

$ su -c /data/adb/modules/zygisksu/zygisk-ptrace64 info
$ su -c /data/adb/modules/zygisksu/zygisk-ptrace32 info

**Comment by CaptainThrowback** [comment]
> > WebUI won't load when Multiple root implementations are used (note that daemon also crashes). See attached video.
> > 2024-07-14-22-23-37.mp4
> 
> Mind posting results of following commands on adb shell or Termux (w/root)?:
> 
> $ su -c /data/adb/modules/zygisksu/zygisk-ptrace64 info
> $ su -c /data/adb/modules/zygisksu/zygisk-ptrace32 info

Sorry, I bricked my test device yesterday, so I won't be able to help.

**Comment by CaptainThrowback** [comment]
> > WebUI won't load when Multiple root implementations are used (note that daemon also crashes). See attached video.
> > 2024-07-14-22-23-37.mp4
> 
> Mind posting results of following commands on adb shell or Termux (w/root)?:
> 
> $ su -c /data/adb/modules/zygisksu/zygisk-ptrace64 info $ su -c /data/adb/modules/zygisksu/zygisk-ptrace32 info

```
~ $ su -c /data/adb/modules/zygisksu/bin/zygisk-ptrace64 info
The ReZygisk Tracer v1.0.0-326-6941cc1-release       
ReZygisk Tracer v1.0.0-326-6941cc1-release           Daemon process PID: -784688060
Is the daemon running: no
~ $ su -c /data/adb/modules/zygisksu/bin/zygisk-ptrace32 info                                             The ReZygisk Tracer v1.0.0-326-6941cc1-release
                                                     ReZygisk Tracer v1.0.0-326-6941cc1-release
Daemon process PID: -198835580                       Is the daemon running: no
~ $
```

**Comment by ThePedroo** [comment]
Superseded by #73.

**Pull request closed without merging**
